### PR TITLE
Various optimizations for static sources

### PR DESCRIPTION
**Pull request by philippjfr**
When an Element is static the ``get_data`` call generally still gets called because in some cases the styling options can still affect the returned data. This PR ensures that any data which definitely has not changed isn't computed in the method. This can result in large performance boosts particularly for large Shape, Path and Polygon Elements, which need to be appropriately unpacked.

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good to me; ready to merge?

**Comment by philippjfr** [comment]
Depends on https://github.com/ioam/holoviews/pull/1952, so we'll have to make sure to pin the holoviews version on the next release.

**Comment by philippjfr** [comment]
Otherwise ready to merge yes.

**Comment by jbednar** [comment]
Let's merge that HV PR ASAP, then!

**Pull request merged**
