### PR TITLE
Add support for MercatorTicker in bokeh

### PR DESCRIPTION
**Pull request by philippjfr**
This PR adds support for the new MercatorTicker in bokeh, mostly addressing this issue: https://github.com/ioam/geoviews/issues/36. Unfortunately it causes various issue when zooming beyond the allowed ranges. I'll have to investigate further to see if bounding the ranges is sufficient to avoid these issues.

### CODE REVIEW

**Comment by jbednar** [comment]
Checking out the lat/lon support has been on my list for a couple of weeks now, but I have yet to try it. :-(

**Comment by philippjfr** [comment]
>Checking out the lat/lon support has been on my list for a couple of weeks now, but I have yet to try it. :-(

You could try this PR, it works well when you're zoomed into some small region but if you try to plot something global, the zoom starts stuttering and the axis ticks mess up pretty badly.

**Comment by jbednar** [comment]
Are there some safeguards that could be put into the Bokeh code to make this safer, so that e.g. ticks just aren't shown when they can't be calculated?

**Comment by philippjfr** [comment]
So I can no longer reproduce many of the issues I had with this initially. The one issue I do still see is that if the plot is larger than the whole globe the ticks do not initialize correctly:

screen shot 2017-09-29 at 7 02 02 pm

However once you zoom in a bit they behave correctly:

screen shot 2017-09-29 at 7 03 24 pm

**Comment by philippjfr** [comment]
I think that behavior is still preferable to having the axis display northings and eastings in meters, which are entirely useless. So I think we should just merge this.

**Pull request merged**
