### PR TITLE
Initial version of roadmap

### PR DESCRIPTION
**Pull request by jbednar**
Anyone have modifications or additions?

Presumably this and the one on PyViz should be linked into the docs somewhere, but I'm not sure where.  Any suggestions?

### CODE REVIEW

**Comment by jbednar** [comment]
Any opinion on where to link this in?  Possibilities:

1. In the main TOC, after User Guide and Gallery and before About
2. Buried as a link under About.
3. In the same list as Gitter, Twitter, and Github.

I vote for 1, but that does make it quite prominent, so others may prefer a less prominent spot.

**Comment by jbednar** [comment]
You can see an example of approach 1 at https://ioam-docs.github.io/pyviz-latest .

**Comment by philippjfr** [comment]
I'm fine with 1.

**Comment by jbednar** [comment]
Ok, I've added a link to the roadmap, so I think this is ready to merge.

**Pull request merged**
